tickers:
  - YDEX
  - OZON
  - SBER
  - LKOH
  - GAZP
  - GMKN
  - ROSN
  - NVTK
  - TATN
  - MTSS
  - MGNT
  - PLZL
  - CHMF
  - DATA
  - T
  - SBMM
  - VTBR
  - RUAL
  - GLDRUB_TOM
  - SLVRUB_TOM
  - CNYRUB_TOM
ollama:
  host: "192.168.88.193:11434"
  model: "qwen3.8"
  timeout: 10s
moex_iss_base_url: "https://iss.moex.com/iss"
algopack_base_url: "https://apim.moex.com/iss/datashop"
storage:
  path: "./trader.db"
risk:
  max_lots: 1
is_paper_trading: true
poll_interval: 5m
telegram:
  chat_id: ""
